### PR TITLE
React unhandled rejection errors

### LINKED ISSUE #350: "Error: Room released before initialization started" when using "@ably/chat/react" providers in my nextjs app.
I have the following layout.tsx:

```tsx
// layout.tsx
import { LobbyRoomProvider } from "@/app/[locale]/(dynamic)/cs/lobby/[room]/_components/lobby-room-provider"
import { getAuthUser } from "@repo/supabase/queries"

interface LobbyLayoutProps {
  children: React.ReactNode
  params: {
    room: string
  }
}
export default async function LobbyLayout({
  children,
  params,
}: LobbyLayoutProps) {
  const { room } = params
  const { data } = await getAuthUser()
  const user = data?.user
  return (
    <LobbyRoomProvider initialRoom={room} initialUser={user}>
      {children}
    </LobbyRoomProvider>
  )
}
```

I then have the following client component which has the ably providers and so on:
```tsx
// lobby-room-provider.tsx
"use client"
import * as Ably from "ably"
import { ChatClientProvider, ChatRoomProvider } from "@ably/chat/react"
import { ChatClient, LogLevel, RoomOptionsDefaults } from "@ably/chat"
import { useMemo } from "react"
import { useUser } from "@supabase/auth-helpers-react"
import type { User } from "@supabase/supabase-js"

interface LobbyRoomProviderProps {
  children: React.ReactNode
  initialUser: User | null
  initialRoom: string
}
export function LobbyRoomProvider(props: LobbyRoomProviderProps) {
  const { children, initialUser, initialRoom } = props
  const clientUser = useUser()
  const user = clientUser ?? initialUser
  const ablyChatRoom = `lobby:${initialRoom}`

  const isLoggedIn = !!user

  const client = useMemo(() => {
    return new Ably.Realtime({
      authUrl: isLoggedIn ? "/api/ably" : undefined,
      autoConnect: typeof window !== "undefined",
      clientId: isLoggedIn ? user.id : undefined,
      key: process.env.NEXT_PUBLIC_ABLY_API_KEY,
      logHandler: console.log,
      logLevel: 2,
    })
  }, [user, isLoggedIn])

  const chatClient = useMemo(() => {
    return new ChatClient(client, {
      logLevel: LogLevel.Info,
      logHandler: console.log,
    })
  }, [client])

  return (
    <ChatClientProvider client={chatClient}>
      <ChatRoomProvider id={ablyChatRoom} options={RoomOptionsDefaults}>
        {children}
      </ChatRoomProvider>
    </ChatClientProvider>
  )
}
```

Loading the app gives me this error immediately:
CleanShot 2024-09-17 at 19 08 36@2x

My logs also show the following error:

```
Ably: Channel state for channel "lobby:1::$chat::$reactions": detached; reason: [_ErrorInfo: Channel detached; statusCode=404; code=90001] 2

```

I was under the impression that it would create the channel for me if it does not exist. Is that not correct?

### PR DESCRIPTION
**Pull request by AndyTWF**
### Context

Fixes #350 

### Description

- Adds a promise rejection handler in ChatRoomProvider to handle unhandled rejections (due to initialization skips)
- Adds a promise rejection handler for getPreviousMessages if the room is released before initialization
- Changes the room release before initialization to use an appropriate error code
- Avoid error logging in usePresenceListener and useTyping if room is released

### Checklist

* [x] QA'd by the author.
* [x] Unit tests created (if applicable).
* [x] Integration tests created (if applicable).
* [x] Follow coding style guidelines found [here](https://github.com/ably/engineering/tree/main/best-practices).
* [x] TypeDoc updated (if applicable).
* [x] (Optional) Update documentation for new features.
* [x] Browser tests created (if applicable).
* [x] In repo demo app updated (if applicable).

### Testing Instructions (Optional)

Open demo app, refresh many times - notice there are no errors (compare to main).

### CODE REVIEW

File: src/core/errors.ts [hunk 1]
```diff
@@ -86,3 +88,6 @@ export enum ErrorCodes {
    */
   RoomLifecycleError = 102105,
 }
+
+// eslint-disable-next-line @typescript-eslint/no-unsafe-enum-comparison
+export const errorInfoIs = (errorInfo: ErrorInfo, error: ErrorCodes): boolean => errorInfo.code === error;
```
Comment (splindsay-92) [inline src/core/errors.ts:93]: Should we typedocs this as it's exported and used elsewhere?

File: src/core/room.ts [hunk 2]
```diff
@@ -188,9 +189,19 @@ export class DefaultRoom implements Room {
     // Room initialization: handle the state before features start to be initialized
     const rejectablePromise = makeRejectablePromise(makeAlwaysResolves(initAfter));
     const initFeaturesAfter = rejectablePromise.promise;
+    // Catch to prevent global errors and print a debug log
```
Comment (vladvelici) [inline src/core/room.ts:192]: This one might not be needed because we always create `_asyncOpsAfter`, which is using `initFeaturesAfter.then(...)` and it is created sync in this constructor, so before `initFeaturesAfter` can be rejected.

`_asyncOpsAfter` has a catch already, at the bottom of the constructor.

File: src/core/errors.ts (hunk 1 above)
Comment (AndyTWF) [reply src/core/errors.ts]: Ah my bad, missed this one - fixed!

File: src/react/hooks/use-presence-listener.ts [hunk 3]
```diff
@@ -201,7 +201,13 @@ export const usePresenceListener = (params?: UsePresenceListenerParams): UsePres
...
       .catch((error: unknown) => {
-        logger.error('usePresenceListener(); error fetching initial presence data', { error, roomId: room.roomId });
+        const errorInfo = error as Ably.ErrorInfo;
+        if (errorInfoIs(errorInfo, ErrorCodes.RoomIsReleased)) return;
+
+        logger.error('usePresenceListener(); error fetching initial presence data', {
+          error,
+          roomId: room.roomId,
+        });
         setErrorState(error as Ably.ErrorInfo);
```
Comment (vladvelici) [inline src/react/hooks/use-presence-listener.ts:211]: nitpick: use the `errorInfo` var here to avoid casting again?

File: test/core/messages.integration.test.ts [hunk 4]
```diff
@@ -441,4 +443,17 @@ describe('messages integration', () => {
...
+    const chat = context.chat;
+    const roomId = randomRoomId();
+    const room = chat.rooms.get(roomId, RoomOptionsDefaults);
+
+    // Create a subscription to messages
+    room.messages.subscribe(() => {});
+
+    // Now release the room
+    // We should not have any unhanded promise rejections
+    await chat.rooms.release(roomId);
```
Comment (vladvelici) [inline test/core/messages.integration.test.ts:457]: Is this test working correctly if there are unhandled promise rejections? Those errors get thrown outside of the normal execution, so they don't typically make anything crash.

Not sure how to listen to them exactly - maybe listening to https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event?

File: test/core/room.test.ts [hunk 5]
```diff
@@ -514,4 +515,11 @@ describe('Room', () => {
     expect(attached).toBe(false);
     expect(attachedError).toBe(true);
   });
+
+  it<TestContext>('can be released immediately without unhandled rejections', async (context) => {
+    const room = context.getRoom(defaultRoomOptions);
+
+    // Release the room
+    await (room as DefaultRoom).release();
```
Comment (vladvelici) [inline test/core/room.test.ts:523]: same as before - does this test actually fail if there are unhandled rejections?

**Review by splindsay-92 — APPROVED** [review]
LGTM!

File: test/core/messages.integration.test.ts (hunk 4 above)
Comment (AndyTWF) [reply test/core/messages.integration.test.ts:457]: The test will still "pass" - unfortunately we can't get around that. But the actual test process will exit with code `1` and will therefore fail CI.

I've added a comment to this effect.

File: test/core/room.test.ts (hunk 5 above)
Comment (AndyTWF) [reply test/core/room.test.ts:523]: As above

File: src/react/hooks/use-presence-listener.ts (hunk 3 above)
Comment (AndyTWF) [reply src/react/hooks/use-presence-listener.ts:211]: Done!

File: src/core/room.ts (hunk 2 above)
Comment (AndyTWF) [reply src/core/room.ts:192]: We'll still need it.

The `initFeaturesAfter.then` and `initFeaturesAfter.catch` calls returns a new promise that executes based on the result of `initFeaturesAfter`.

So the call to `initFeaturesAfter.catch` here is one promise chain, `_asyncOpsAfter` is another separate one. Both of them will reject if `_initFeaturesAfter` rejects.

If we wanted to not have this behaviour, then `initFeaturesAfter` would have to be set to the value of `initFeaturesAfter.catch(...)` - which I don't think is desirable.

Comment (AndyTWF) [reply src/core/room.ts]: Yeah - I've removed it and left a comment to that effect.

**Review by vladvelici — APPROVED** [review]
