### PR TITLE
core/room: add channel manager, fix bug where channel options not applied

### LINKED ISSUE #411: Channel options / modes overwritten
At the moment, channel options / modes on shared channels are determined by LWW. So if you have all the features, the options provided by occupancy override those provided by presence.

Shared channels need to be configured such that they merge the modes required by each feature and request the channel only once.

This also requires a new specification point.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/CHA-738) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by AndyTWF**
### Context

Closes #411
[CHA-738].

### Description

This change fixes the bug described in #411 whereby channel options are overwritten by successive uses of the same channel, rather than merged together.

In doing this, we also fix the bug in relation to newly introduce spec point CHA-RC3. We were previously depending on the soft-deprecated behaviour in RTS3c which would allow you to update channel options via setOptions.

The change is achieved by adding a channel manager, whose job it is to register all the options for a given channel prior to the first channels.get() call, and call channels.get with the amalgamated options.

### Checklist

* [x] QA'd by the author.
* [x] Unit tests created (if applicable).
* [x] Integration tests created (if applicable).
* [x] Follow coding style guidelines found [here](https://github.com/ably/engineering/tree/main/best-practices).
* [x] TypeDoc updated (if applicable).
* [x] (Optional) Update documentation for new features.
* [x] Browser tests created (if applicable).
* [x] In repo demo app updated (if applicable).

### Testing Instructions (Optional)

N/A

[CHA-738]: https://ably.atlassian.net/browse/CHA-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by AndyTWF** [comment]
Note, we shouldn't merge this until RAR-815 lands.

File: src/core/channel-manager.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  get(channelName: string): Ably.RealtimeChannel {
+    this._logger.trace('ChannelManager.get();', { channelName });
+    this._requestedChannels.add(channelName);
+    return this._realtime.channels.get(
+      channelName,
+      this._registeredOptions.get(channelName) ?? DEFAULT_CHANNEL_OPTIONS,
+    );
+  }
+
+  release(channelName: string): void {
```
Comment (owenpearson) [inline src/core/channel-manager.ts:40]: do we need to also `this._requestedChannels.delete(channelName)` here?

**Review by owenpearson — COMMENTED** [review]
looks good, just one question:

File: src/core/channel-manager.ts (hunk 1 above)
Comment (AndyTWF) [reply src/core/channel-manager.ts:40]: Fair shout - done!

**Review by owenpearson — APPROVED** [review]
looks good!

**Review by JoaoDiasAbly — APPROVED** [review]
