### PR TITLE
Room lifecycle in progress flag

### LINKED ISSUE #406: [RoomLifeCycleManager] `_operationInProgress` flag incorrectly set
- Currently, `operationInProgress` flag is [set to false only when `attach` operation finishes.](https://github.com/ably/ably-chat-js/blob/533c4d0314bcce942a30b4d7d6a012c3b081420d/src/core/room-lifecycle-manager.ts#L592) 
- It should be set `false` at the end of other operations like `Detach`, `Release`, and `Internal` operations.
- Also, not sure if we really need this code snippet in place 
https://github.com/ably/ably-chat-js/blob/533c4d0314bcce942a30b4d7d6a012c3b081420d/src/core/room-lifecycle-manager.ts#L130-L134
- This sets `operationInProgress` to `true` when the room has just initialized and not performing any operation.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/CHA-723) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by AndyTWF**
### Context

Closes #406 
[CHA-723]

### Description

We weren't properly setting and unsetting the room operation in progress flag (we were only setting it to false when attaching). This change rectifies this.

Also included is the fix for async-mutex operation precedence - as the order was the wrong way around.

### Checklist

* [x] QA'd by the author.
* [x] Unit tests created (if applicable).
* [x] Integration tests created (if applicable).
* [x] Follow coding style guidelines found [here](https://github.com/ably/engineering/tree/main/best-practices).
* [x] TypeDoc updated (if applicable).
* [x] (Optional) Update documentation for new features.
* [x] Browser tests created (if applicable).
* [x] In repo demo app updated (if applicable).

### Testing Instructions (Optional)

N/A

[CHA-723]: https://ably.atlassian.net/browse/CHA-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sacOO7 — COMMENTED** [review]
Can we add a private method to avoid code repetition 
```
  atomic(operation: () => Promise<void>, priority: number): Promise<void> {
      return this._mtx.runExclusive(() => {
        this._operationInProgress = true
        return operation().finally(() =>
          this._operationInProgress = false
        )
      }, priority);
  }
```
So, attach and all other ops would be
```
  attach(): Promise<void> {
    this._logger.trace('RoomLifecycleManager.attach();');
    return this.atomic(async () => {
```

**Comment by sacOO7** [comment]
> > Can we add a private method to avoid code repetition
> 
> We can in the future - though I'd prefer to keep this PR scoped to just the functionality fixes for now.

Sure, I mean, the suggestion is related to the fix. In the future, if we have more atomic operations, we don't need to worry about setting/clearing `_operationInProgress` flag.

**Comment by sacOO7** [comment]
Sure, thanks for the info!

File: src/core/room-lifecycle-manager.ts [hunk 1]
```diff
@@ -404,6 +405,8 @@ export class RoomLifecycleManager {
     try {
       await this._doChannelWindDown(contributor).catch(() => {
         // If in doing the wind down, we've entered failed state, then it's game over anyway
+        // TODO: Another PR, but in the even if we get a failed channel, we still need to do the wind down
```
Comment (splindsay-92) [inline src/core/room-lifecycle-manager.ts:408]: Is the other PR already in review, or still to be started? If it's the former, can you add it to the PR body please?

Comment (AndyTWF) [reply src/core/room-lifecycle-manager.ts:408]: Not yet started, but now added an issue link

File: src/core/room-lifecycle-manager.ts [hunk 2]
```diff
@@ -417,27 +420,32 @@ export class RoomLifecycleManager {
       });
     } catch {
       // If an error gets through here, then the room has entered the failed state, we're done.
+      this._endLifecycleOperation();
       return;
     }
 
     // If our problem channel has reattached, then we can retry the attach
-    if (contributor.channel.state === RoomStatus.Attached) {
+    if (contributor.channel.state === 'attached') {
```
[the remark this answers is not in the document]
Comment (AndyTWF) [reply src/core/room-lifecycle-manager.ts:429]: They were previously an improper type comparison - the channel states are just strings, not enums (it works as the enum is a superset, but its not a proper comparison)

**Review by splindsay-92 — APPROVED** [review]
LGTM
